### PR TITLE
Added validations, replaced bluebird and unirest

### PR DESCRIPTION
**Pull request by StephanGeorg**
Added some validations before executing the API in terms of speed and API usage. Replaced unirest with request and removed Bluebird. Can you tell me what is the advantage not to use the default promises?

### CODE REVIEW

**Comment by sabarasaba** [comment]
Changes look good man, thanks for helping!

When this module was written, node was in 0.12 and it just added native promises. But due to a [memory leak issue](https://github.com/tj/co/issues/180), I ended up going for bluebird in order to avoid the issue.

**Comment by sabarasaba** [comment]
@StephanGeorg Actually, theres one more thing. Could you also update the readme.md file ? it seems to have a reference to bluebird. Cheers!

**Comment by StephanGeorg** [comment]
I removed the references to unirest and bluebird and some other. Would you please update the npm package as well?

**Comment by sabarasaba** [comment]
Sweet, I just asked @freyfogle to make me a contributor of the repo so that I can republish the package. Lets wait a bit until he sees these messages! Again, thanks a lot dude !

**Comment by freyfogle** [comment]
ok I think I gave you access. frankly I find github teams and organizations so confusing

**Comment by sabarasaba** [comment]
yeah, i got it now! will publish the package in a few min.

**Comment by sabarasaba** [comment]
@StephanGeorg just published the package and fixed one of the tests that was broken. Thanks !

**Comment by StephanGeorg** [comment]
Cool, thanks!

**Pull request merged**
